export const whats = [
    { type: "For Rent", value: 131 },
    { type: "For Sale", value: 130 },
    { type: "Landlord Reviews", value: 135 },
    { type: "Roommates Wanted", value: 132 },
  ];
 export const propertyTypes = [
    { type: "All", value: 172 },
    { type: "House", value: 170 },
    { type: "Apartment", value: 171 },
    { type: "Condo", value: 173 },
    { type: "Houseboat", value: 174 },
    { type: "Townhouse", value: 175 },
    { type: "Boat", value: 176 },
  ];
 export const beds = [
    { type: "All", value: 139 },
    { type: "1", value: 138 },
    { type: "2", value: 141 },
    { type: "3", value: 142 },
    { type: "4", value: 143 },
    { type: "Studio", value: 163 },
  ];
 export const bathrooms = [
    { type: "All", value: 140 },
    { type: "0.5", value: 137 },
    { type: "1", value: 144 },
    { type: "1.5", value: 145 },
    { type: "2", value: 146 },
    { type: "3", value: 164 },
  ];
 export const cities = [
    { name: "Seattle", value: 165 },
    { name: "Bellevue", value: 166 },
    { name: "Tacoma", value: 167 },
    { name: "Everett", value: 168 },
    { name: "Redmond", value: 178 },
  ];
 export const neighborhoods = [
    { name: "Everywhere", value: 109 },
    { name: "Queen-Anne", value: 40 },
    { name: "Fremont", value: 41 },
    { name: "Uptown", value: 42 },
    { name: "Pioneer-Square", value: 43 },
    { name: "University-of-Washington", value: 44 },
    { name: "SODO", value: 45 },
    { name: "University-District", value: 46 },
    { name: "Downtown-Seattle", value: 47 },
    { name: "First-Hill", value: 48 },
    { name: "Adams", value: 49 },
    { name: "Highline", value: 50 },
    { name: "Rainier-Valley", value: 51 },
    { name: "Greater-Duwamish", value: 52 },
    { name: "South-Lake-Union", value: 53 },
    { name: "Northgate", value: 54 },
    { name: "Richmond-Highlands", value: 55 },
    { name: "Loyal-Heights", value: 56 },
    { name: "Greenwood", value: 57 },
    { name: "Green-Lake", value: 58 },
    { name: "Woodland-Park-Avenue-North", value: 59 },
    { name: "Phinney-Ridge", value: 60 },
    { name: "Crown-Hill", value: 61 },
    { name: "Victory-Heights", value: 62 },
    { name: "Wedgwood", value: 63 },
    { name: "Whitman-Avenue-North", value: 64 },
    { name: "Maple-Leaf", value: 65 },
    { name: "Ballard", value: 66 },
    { name: "West-Woodland", value: 67 },
    { name: "Magnolia", value: 68 },
    { name: "Southeast-Magnolia", value: 69 },
    { name: "King-County", value: 70 },
    { name: "Interbay", value: 71 },
    { name: "North-Queen-Anne", value: 72 },
    { name: "Thorndyke-Avenue-West", value: 73 },
    { name: "Brighton", value: 74 },
    { name: "Rainier-Vista", value: 76 },
    { name: "Dunlap", value: 77 },
    { name: "Rainier-Beach", value: 78 },
    { name: "West-Seattle", value: 79 },
    { name: "Mount-Baker", value: 80 },
    { name: "Mid-Beacon-Hill", value: 81 },
    { name: "North-Admiral", value: 82 },
    { name: "Fairmount-Park", value: 83 },
    { name: "Delridge-Way-Southwest", value: 84 },
    { name: "High-Point", value: 85 },
    { name: "Fauntleroy-Way-Southwest", value: 86 },
    { name: "New-Holly", value: 87 },
    { name: "Junction", value: 88 },
    { name: "2nd-Avenue", value: 89 },
    { name: "Yesler-Terrace", value: 90 },
    { name: "6th-Avenue-South", value: 91 },
    { name: "Central-District", value: 92 },
    { name: "University-Heights", value: 93 },
    { name: "7th-Avenue-Northeast", value: 94 },
    { name: "University-Way-Northeast", value: 95 },
    { name: "Ravenna", value: 96 },
    { name: "Northeast-Blakeley-Street", value: 97 },
    { name: "Roosevelt", value: 98 },
    { name: "Capitol-Hill", value: 99 },
    { name: "Bellevue-Avenue-East", value: 100 },
    { name: "Stevens", value: 101 },
    { name: "Miller-Park", value: 102 },
    { name: "12th-Avenue", value: 103 },
    { name: "East-Queen-Anne", value: 104 },
    { name: "West-Queen-Anne", value: 105 },
    { name: "Minor", value: 106 },
  ];

 export const options = [
    "Cats",
    "Dogs",
    "Balcony",
    "Parking",
    "MFTE"
  ]
